name: Test
on:
    workflow_call:
        inputs:
            coverage:
                type: boolean
                default: true
                required: false
jobs:
    test:
        name: Test
        runs-on: ubuntu-22.04
        steps:
            - name: Check out Git repository
              uses: actions/checkout@v4.2.2
            - name: Set up Node.js
              uses: actions/setup-node@v4.4.0
              with:
                  node-version: 22
                  cache: npm
            - name: Install Node.js dependencies
              run: npm ci
            - name: Test package
              run: npm test ${{ inputs.coverage && '-- --coverage' || '' }}
            - name: Upload coverage HTML report
              if: ${{ inputs.coverage }}
              uses: actions/upload-artifact@v4.4.3
              with:
                  name: coverage-html-report
                  path: ./.coverage/lcov-report/
                  if-no-files-found: error
                  include-hidden-files: true
